### ISSUE TITLE
Orb not compatible with legacy google project id naming

### ISSUE THREAD

**Issue by carlosmuvi** [horie1024/orb_firebaae_test_lab#2]
Amazing job with this orb! really useful.

However, since the `bucket-name` is hardcoded to append the `google-project-id`, and the old project ids contain characters that cannot be part of the `bucket-name`, it crashes due to invalid characters (check the screenshot below).

Solution - Remove the append and just leave the bucket name property:

`--results-bucket <<parameters.bucket_name>>`

Check error below.

![image](https://user-images.githubusercontent.com/625017/54118605-542b2500-43eb-11e9-87d9-8fb69c04e5ce.png)

**Comment by horie1024** [comment]
@carlosmuvi 
Thank you for reporting the issue. And i'm sorry for reply too late.

I fixed this issue and release [horie1024/firebase-test-lab@0.0.3](https://circleci.com/orbs/registry/orb/horie1024/firebase-test-lab)
